---
abstract: 'use Moose or Mouse modules'
author:
  - 'Shawn M Moore <sartak@bestpractical.com>'
  - 'Florian Ragwitz <rafl@debian.org>'
  - 'Stevan Little <stevan@iinteractive.com>'
  - 'Tokuhiro Matsuno <tokuhirom@gmail.com>'
  - 'Goro Fuji <gfuji@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.31
generated_by: 'Dist::Zilla version 2.100921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Any-Moose
recommends: {}
requires:
  Mouse: 0.40
  perl: 5.006_002
version: 0.13
