--- 
abstract: use Moose or Mouse modules
author: 
  - Shawn M Moore <sartak@bestpractical.com>
  - Florian Ragwitz <rafl@debian.org>
  - Stevan Little <stevan@iinteractive.com>
  - Tokuhiro Matsuno <tokuhirom@gmail.com>
generated_by: Dist::Zilla::Plugin::MetaYaml version 1.004
license: perl
name: Any-Moose
requires: 
  Mouse: 0.20
version: 0.07
